### PR TITLE
fix build and bump joomla version

### PR DESCRIPTION
**Pull request by OnGle**

### CODE REVIEW

**Comment by JedMeister** [comment]
LGTM! :)

**Review by Christie018 — APPROVED** [review]
I went through and reviewed the source code for the appliance update and the version changes. The code changes to bump up the joomla version seem okay and are documented in the changelog. The only comment I would have is similar to joomla3 in which the libinithooks update in joomla4.py should be switched around so that the import statements are in the correct order.

**Comment by JedMeister** [comment]
Haha! I just realised that this PR is against your own Joomla fork @OnGle! Regardless, now we've given it approval, I'll create a new PR against the TurnKey repo.

**Comment by JedMeister** [comment]
Oh, I see why. The TurnKey repo isn't a fork of this one...

Once I open the new PR in the TurnKey repo, can you please destroy this repo (or at least rename it). Then you can fork the TurnKey one to make future updates easier for all of us! :)

**Pull request closed without merging**
